# Generated by Django 5.2.12 on 2026-05-25 04:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0032_add_trial_lesson_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Денормализованный баланс. Источник правды — Transaction ledger.', max_digits=14, verbose_name='Баланс')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Валюта')),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя транзакция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Кошелёк',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Знаковая сумма: > 0 — зачисление, < 0 — списание.', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Снимок баланса кошелька после применения транзакции.', max_digits=14)),
                ('type', models.CharField(choices=[('deposit', 'Пополнение баланса'), ('refund', 'Возврат за неиспользованные уроки'), ('lesson_payout', 'Выплата учителю за урок'), ('commission', 'Комиссия платформы (доход)'), ('adjustment_in', 'Корректировка (зачисление)'), ('purchase', 'Покупка подписки'), ('withdrawal', 'Вывод средств'), ('commission_deduct', 'Удержание комиссии'), ('adjustment_out', 'Корректировка (списание)')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершена'), ('reversed', 'Отменена')], default='completed', max_length=16)),
                ('idempotency_key', models.CharField(help_text='Уникальный ключ операции. Повторный вызов с тем же ключом — no-op.', max_length=128, unique=True)),
                ('reference', models.CharField(blank=True, default='', help_text='Внешний ID операции (например, payment_id от Payme/Click).', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teachers.booking')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.wallet')),
            ],
            options={
                'verbose_name': 'Финансовая транзакция',
                'verbose_name_plural': 'Финансовые транзакции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0'))), name='wallet_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='billing_tra_wallet__6c38e4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status'], name='billing_tra_type_69ac37_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_booking'], name='billing_tra_related_798bcf_idx'),
        ),
    ]
