# Generated by Django 5.2.12 on 2026-05-25 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_backfill_wallets'),
        ('teachers', '0032_add_trial_lesson_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Опционально: «Базовый», «Стандарт», «Премиум».', max_length=80)),
                ('description', models.TextField(blank=True, default='', help_text='Чему ученик научится за этот тариф (опционально).')),
                ('lessons_per_week', models.PositiveSmallIntegerField(choices=[(1, '1 в неделю'), (2, '2 в неделю'), (3, '3 в неделю'), (4, '4 в неделю'), (5, '5 в неделю')], default=2)),
                ('lesson_duration_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 минут'), (45, '45 минут'), (60, '60 минут'), (90, '90 минут')], default=60)),
                ('duration_months', models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (2, '2 месяца'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], default=1, help_text='Срок подписки в месяцах (минимум 1).')),
                ('price_per_month', models.DecimalField(decimal_places=2, help_text='Цена за 1 месяц этого тарифа в сумах.', max_digits=14)),
                ('is_active', models.BooleanField(default=True, help_text='Если выключен — нельзя купить, но активные подписки продолжают работать.')),
                ('is_recommended', models.BooleanField(default=False, help_text='Учитель помечает один тариф как рекомендованный — выделяется в UI.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения (меньше = выше).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tariffs', to='teachers.subject', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='teachers.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['sort_order', '-is_recommended', 'price_per_month'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='billing_tar_teacher_8968f0_idx'), models.Index(fields=['subject', 'is_active'], name='billing_tar_subject_4c0867_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_per_month__gt', 0)), name='tariff_price_positive'), models.CheckConstraint(condition=models.Q(('lessons_per_week__gte', 1), ('lessons_per_week__lte', 7)), name='tariff_lessons_per_week_range'), models.CheckConstraint(condition=models.Q(('duration_months__gte', 1), ('duration_months__lte', 24)), name='tariff_duration_months_range')],
            },
        ),
    ]
