# Generated by Django 5.2.12 on 2026-05-25 04:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_tariff'),
        ('teachers', '0032_add_trial_lesson_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Ожидает оплаты'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена (все уроки)'), ('expired', 'Истёкла (срок вышел)'), ('cancelled_by_student', 'Отменена учеником'), ('cancelled_by_teacher', 'Отменена учителем'), ('cancelled_by_admin', 'Отменена администрацией')], db_index=True, default='pending_payment', max_length=24)),
                ('lessons_per_week', models.PositiveSmallIntegerField()),
                ('lesson_duration_minutes', models.PositiveSmallIntegerField()),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('total_lessons', models.PositiveIntegerField(help_text='Сколько уроков всего по этой подписке.')),
                ('price_total', models.DecimalField(decimal_places=2, help_text='Полная стоимость подписки в момент покупки.', max_digits=14)),
                ('price_per_lesson', models.DecimalField(decimal_places=2, help_text='Стоимость одного урока = price_total / total_lessons.', max_digits=14)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Доля платформы в payout (0..1). Snapshot на момент покупки.', max_digits=5)),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Сколько денег ещё лежит в эскроу платформы по этой подписке.', max_digits=14)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('lessons_paid_out', models.PositiveIntegerField(default=0, help_text='Сколько уроков уже выплачено учителю (после grace window).')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_idempotency_key', models.CharField(help_text='Гарантирует один Subscription при повторных submit.', max_length=128, unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='teachers.subject')),
                ('tariff', models.ForeignKey(blank=True, help_text='Из какого тарифа куплено. Может быть NULL, если тариф удалён.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='billing.tariff')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscription'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['related_subscription'], name='billing_tra_related_90b9ee_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['student', 'status'], name='billing_sub_student_2c3af7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['teacher', 'status'], name='billing_sub_teacher_1103f9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', '-created_at'], name='billing_sub_status_a7f58f_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('escrow_balance__gte', Decimal('0'))), name='subscription_escrow_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('total_lessons__gt', 0)), name='subscription_total_lessons_positive'),
        ),
    ]
