# Generated by Django 5.2.12 on 2026-05-25 05:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_transaction_related_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('approved', 'Одобрена (перевод в процессе)'), ('completed', 'Выполнена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена пользователем')], db_index=True, default='pending', max_length=16)),
                ('payout_method', models.CharField(choices=[('card', 'Карта (UzCard / Humo / Visa)'), ('phone', 'На номер телефона'), ('other', 'Другое')], default='card', max_length=10)),
                ('payout_details', models.CharField(help_text='Номер карты / номер телефона / другие реквизиты.', max_length=200)),
                ('comment', models.TextField(blank=True, default='', max_length=500)),
                ('admin_note', models.TextField(blank=True, default='', max_length=1000)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(help_text='Защита от двойного submit формы.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Админ, который последним менял статус.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка на вывод средств',
                'verbose_name_plural': 'Заявки на вывод средств',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='billing_wit_user_id_b3a026_idx'), models.Index(fields=['status', '-created_at'], name='billing_wit_status_2337ea_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='withdrawal_amount_positive')],
            },
        ),
    ]
