# Generated by Django 5.2.12 on 2026-05-25 05:36

import billing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_withdrawalrequest'),
        ('teachers', '0034_alter_review_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('due_at', models.DateTimeField(blank=True, help_text='Опциональный дедлайн.', null=True)),
                ('status', models.CharField(choices=[('assigned', 'Задано'), ('submitted', 'Сдано на проверку'), ('graded', 'Проверено'), ('returned', 'Возвращено на доработку')], db_index=True, default='assigned', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_received', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='billing.subscription')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks_assigned', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=billing.models._homework_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Размер в байтах')),
                ('mime_type', models.CharField(blank=True, default='', max_length=80)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='billing.homework')),
            ],
            options={
                'verbose_name': 'Файл задания',
                'verbose_name_plural': 'Файлы заданий',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_response', models.TextField(blank=True, default='', max_length=5000)),
                ('grade', models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 0 до 100.', null=True)),
                ('feedback', models.TextField(blank=True, default='', max_length=2000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='billing.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homework_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сдача ДЗ',
                'verbose_name_plural': 'Сдачи ДЗ',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=billing.models._submission_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(blank=True, default='', max_length=80)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='billing.homeworksubmission')),
            ],
            options={
                'verbose_name': 'Файл сдачи',
                'verbose_name_plural': 'Файлы сдач',
            },
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['subscription', '-created_at'], name='billing_hom_subscri_1653a5_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['teacher', 'status'], name='billing_hom_teacher_8593eb_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['student', 'status'], name='billing_hom_student_a48dde_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('grade__isnull', True), models.Q(('grade__gte', 0), ('grade__lte', 100)), _connector='OR'), name='hw_submission_grade_range'),
        ),
    ]
