# Generated by Django 5.2.12 on 2026-06-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_homework_homeworkattachment_homeworksubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='approval_expires_at',
            field=models.DateTimeField(blank=True, help_text='Дедлайн оплаты одобренной заявки (после — EXPIRED).', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Когда учитель подтвердил заявку на обучение.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='preferred_schedule',
            field=models.TextField(blank=True, default='', help_text='Предпочтительное расписание/пожелания ученика из заявки.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='weekly_pattern',
            field=models.JSONField(blank=True, default=None, help_text='Подтверждённый недельный шаблон броней: [{"day":"monday","time":"18:00"}, ...].', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Ожидает подтверждения учителя'), ('pending_payment', 'Одобрена, ожидает оплаты'), ('active', 'Активна'), ('paused', 'Приостановлена'), ('completed', 'Завершена (все уроки)'), ('expired', 'Истёкла (срок вышел)'), ('cancelled_by_student', 'Отменена учеником'), ('cancelled_by_teacher', 'Отклонена/отменена учителем'), ('cancelled_by_admin', 'Отменена администрацией')], db_index=True, default='pending_payment', max_length=24),
        ),
    ]
