# Generated by Django 5.2.12 on 2026-06-02 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_subscription_approval_expires_at_and_more'),
        ('teachers', '0036_booking_student_joined_at_booking_teacher_joined_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('resolved_refund', 'Решён в пользу ученика (возврат)'), ('resolved_rejected', 'Отклонён (выплата учителю)'), ('cancelled', 'Отозван учеником')], db_index=True, default='open', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='teachers.booking')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Спор по уроку',
                'verbose_name_plural': 'Споры по урокам',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='billing_les_status_b9a79c_idx')],
            },
        ),
    ]
