# Generated by Django 5.2.12 on 2026-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_lessondispute'),
        ('teachers', '0037_booking_student_present_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='billing_tra_type_69ac37_idx',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'type', 'status'], name='billing_tra_wallet__b92b14_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status', '-created_at'], name='billing_tra_type_4d27a1_idx'),
        ),
    ]
