# Generated by Django 5.2.12 on 2026-06-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_transaction_billing_tra_type_69ac37_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reschedules_period',
            field=models.CharField(blank=True, default='', help_text='Месяц действия счётчика переносов в формате YYYY-MM.', max_length=7),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reschedules_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
