# Generated by Django 5.2.12 on 2026-06-04 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_subscription_paused_at'),
        ('teachers', '0042_notification_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedTrialSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_trial_suggestions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Скрытое предложение пробного',
                'verbose_name_plural': 'Скрытые предложения пробного',
                'indexes': [models.Index(fields=['student'], name='billing_dis_student_e7d613_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'teacher', 'subject'), name='uniq_dismissed_trial_per_student_teacher_subject')],
            },
        ),
    ]
