# Generated by Django 5.2.12 on 2026-06-05 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_dismissedtrialsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MulticardInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма пополнения в сумах (UZS).', max_digits=14)),
                ('store_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('progress', 'В обработке'), ('success', 'Оплачен'), ('error', 'Ошибка'), ('revert', 'Возврат'), ('hold', 'Холдирование')], default='progress', max_length=16)),
                ('multicard_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=512)),
                ('short_link', models.CharField(blank=True, default='', max_length=255)),
                ('card_pan', models.CharField(blank=True, default='', max_length=32)),
                ('ps', models.CharField(blank=True, default='', max_length=32)),
                ('receipt_url', models.URLField(blank=True, default='', max_length=512)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multicard_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инвойс Multicard',
                'verbose_name_plural': 'Инвойсы Multicard',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='billing_mul_user_id_2f21aa_idx'), models.Index(fields=['status'], name='billing_mul_status_3c08a0_idx')],
            },
        ),
    ]
