# Generated by Django 5.2.12 on 2026-06-06 18:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_multicardinvoice'),
        ('teachers', '0044_lessonfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', Decimal('0')), ('commission_rate__lte', Decimal('1'))), name='subscription_commission_rate_0_1'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_approval', 'pending_payment', 'active', 'paused'])), fields=('student', 'teacher', 'subject'), name='uniq_active_subscription_per_triple'),
        ),
    ]
