# Generated by Django 5.2.12 on 2026-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_multicardinvoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
