# Generated by Django 5.2.12 on 2026-07-19 04:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_homework_reminder_sent_at'),
        ('teachers', '0059_support_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Снапшот суммы на момент бронирования.', max_digits=12, verbose_name='Сумма депозита')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Внесён (удержан)'), ('used', 'Зачтён в оплату урока'), ('forfeited', 'Сгорел (неявка)'), ('refunded', 'Возвращён')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='teachers.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Депозит за урок',
                'verbose_name_plural': 'Депозиты за уроки',
                'indexes': [models.Index(fields=['status'], name='billing_boo_status_15552f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='bookingdeposit_amount_positive')],
            },
        ),
    ]
