# Generated by Django 5.2.6 on 2025-09-30 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль учителя', 'verbose_name_plural': 'Профили учителей'},
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='moderation_comment',
            field=models.TextField(blank=True, help_text='Причина отклонения или рекомендации', verbose_name='Комментарий модератора'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='moderation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
