# Generated by Django 5.2.6 on 2025-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_languages',
            field=models.CharField(blank=True, default='ru', help_text='Коды языков через запятую (uz,ru,en)', max_length=100),
        ),
    ]
