# Generated by Django 5.2.6 on 2025-10-11 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacherprofile_teaching_languages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль ученика', 'verbose_name_plural': 'Профили учеников'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='available_weekdays',
            field=models.CharField(blank=True, default='1,2,3,4,5,6,7', help_text='Дни недели через запятую (1-7)', max_length=20, verbose_name='Доступные дни недели'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная цена, которую готов платить', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальный бюджет (сум/час)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная цена, которую готов платить', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный бюджет (сум/час)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите о своих целях обучения, уровне подготовки и ожиданиях', max_length=1000, verbose_name='Описание целей и пожеланий'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='desired_subjects',
            field=models.ManyToManyField(blank=True, help_text='Предметы для изучения', related_name='learning_students', to='teachers.subject'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ищет ли ученик учителя в данный момент', verbose_name='Активный профиль'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('both', 'Онлайн и офлайн')], default='both', max_length=10, verbose_name='Предпочитаемый формат обучения'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Интересующие предметы', related_name='interested_students', to='teachers.subject'),
        ),
    ]
