# Generated by Django 5.2.6 on 2025-10-13 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткое описание о себе', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'PhD'), ('other', 'Другое')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('teacher', 'Профиль учителя'), ('student', 'Профиль ученика')], max_length=10, verbose_name='Тип профиля')),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес просмотревшего')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время просмотра')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent браузера')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='teachers.studentprofile', verbose_name='Профиль ученика')),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to='teachers.teacherprofile', verbose_name='Профиль учителя')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_views_made', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (если авторизован)')),
            ],
            options={
                'verbose_name': 'Просмотр профиля',
                'verbose_name_plural': 'Просмотры профилей',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='teachers_pr_viewed__bdfade_idx'), models.Index(fields=['teacher_profile', '-viewed_at'], name='teachers_pr_teacher_59af3b_idx'), models.Index(fields=['student_profile', '-viewed_at'], name='teachers_pr_student_da7861_idx'), models.Index(fields=['viewer_ip', '-viewed_at'], name='teachers_pr_viewer__7fdf76_idx')],
            },
        ),
    ]
