# Generated by Django 5.2.6 on 2025-10-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacherprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ваш Telegram username (@username) или номер телефона', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер WhatsApp для связи (+998 90 123 45 67)', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
