# Generated by Django 5.2.6 on 2025-10-24 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_studentprofile_telegram_studentprofile_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный ID пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username в Telegram')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='Имя в Telegram')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Фамилия в Telegram')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык интерфейса')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('started_bot', models.BooleanField(default=False, verbose_name='Нажал Start в боте')),
                ('last_interaction', models.DateTimeField(auto_now=True, verbose_name='Последнее взаимодействие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации в боте')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['telegram_id'], name='teachers_te_telegra_31c342_idx'), models.Index(fields=['telegram_username'], name='teachers_te_telegra_93afae_idx')],
            },
        ),
    ]
