# Generated by Django 5.2.6 on 2025-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_telegramuser'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['is_active', '-created_at'], name='teachers_st_is_acti_e86c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['city', 'is_active'], name='teachers_st_city_id_fb5f85_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['learning_format'], name='teachers_st_learnin_f7b549_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['education_level'], name='teachers_st_educati_ac135e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['budget_min', 'budget_max'], name='teachers_st_budget__3b12a6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['-rating', '-created_at'], name='teachers_te_rating_1f9bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['is_active', 'moderation_status'], name='teachers_te_is_acti_888bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['city', 'is_active'], name='teachers_te_city_id_75b731_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['teaching_format'], name='teachers_te_teachin_7b4906_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['experience_years'], name='teachers_te_experie_92ca87_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubject',
            index=models.Index(fields=['teacher', 'hourly_rate'], name='teachers_te_teacher_c59753_idx'),
        ),
        migrations.AddIndex(
            model_name='teachersubject',
            index=models.Index(fields=['subject'], name='teachers_te_subject_fd5884_idx'),
        ),
    ]
