# Generated by Django 5.2.6 on 2025-10-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_teachers', to='teachers.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_students', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Избранный ученик',
                'verbose_name_plural': 'Избранные ученики',
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
