# Generated by Django 4.2 on 2025-11-03 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_favoritestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_message', 'Новое сообщение'), ('new_review', 'Новый отзыв'), ('profile_view', 'Просмотр профиля'), ('system', 'Системное уведомление'), ('broadcast', 'Массовая рассылка')], default='new_message', max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('data', models.JSONField(blank=True, default=dict, help_text='JSON с доп. информацией (sender_id, conversation_id, url и т.д.)', verbose_name='Дополнительные данные')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('processing', 'В обработке'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('max_retries', models.PositiveIntegerField(default=5, verbose_name='Максимум попыток')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Время когда уведомление должно быть отправлено', verbose_name='Запланировано на')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Уникальный ключ для предотвращения дублирования', max_length=255, unique=True, verbose_name='Ключ идемпотентности')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление в очереди',
                'verbose_name_plural': 'Очередь уведомлений',
                'ordering': ['scheduled_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Номер попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('skipped', 'Пропущено')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID сообщения в Telegram')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Данные ответа')),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время обработки (мс)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время попытки')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='teachers.notificationqueue', verbose_name='Уведомление')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['status', 'scheduled_at'], name='teachers_no_status_39735c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['recipient', 'status'], name='teachers_no_recipie_5bb15c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['notification_type', 'status'], name='teachers_no_notific_12a42f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationqueue',
            index=models.Index(fields=['idempotency_key'], name='teachers_no_idempot_6320ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification', '-timestamp'], name='teachers_no_notific_7a36c6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', '-timestamp'], name='teachers_no_status_a52725_idx'),
        ),
    ]
