# Generated by Django 4.2 on 2025-11-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_notificationqueue_notificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('page', models.CharField(max_length=100)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.DateField()),
            ],
            options={
                'unique_together': {('ip_address', 'user_agent', 'page', 'month')},
            },
        ),
    ]
