# Generated by Django 4.2 on 2025-11-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_notificationqueue_notificationlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название сохраненного поиска (например: 'Математика в Ташкенте')", max_length=100, verbose_name='Название')),
                ('filters_json', models.JSONField(default=dict, help_text='Другие фильтры (цена, формат, рейтинг и т.д.)', verbose_name='Фильтры')),
                ('notification_enabled', models.BooleanField(default=False, help_text='Получать уведомления о новых учителях по этому поиску', verbose_name='Уведомления включены')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Последнее использование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сохраненный поиск',
                'verbose_name_plural': 'Сохраненные поиски',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('icon', models.CharField(default='fas fa-book', help_text='Font Awesome класс иконки (например: fas fa-calculator)', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#3B82F6', help_text='HEX код цвета (например: #3B82F6)', max_length=7, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше = выше)', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория предметов',
                'verbose_name_plural': 'Категории предметов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Ключ сессии для анонимных пользователей', max_length=40, verbose_name='Ключ сессии')),
                ('search_query', models.CharField(blank=True, help_text='Текстовый запрос, если был использован поиск', max_length=200, verbose_name='Поисковый запрос')),
                ('result_count', models.PositiveIntegerField(default=0, help_text='Количество найденных учителей', verbose_name='Найдено результатов')),
                ('filters_used', models.JSONField(blank=True, default=dict, help_text='Использованные фильтры (город, цена, формат и т.д.)', verbose_name='Использованные фильтры')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Лог поиска предмета',
                'verbose_name_plural': 'Логи поиска предметов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Показывать в блоке 'Популярные предметы'", verbose_name='Популярный'),
        ),
        migrations.AddField(
            model_name='subject',
            name='search_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество поисков по этому предмету', verbose_name='Поиски'),
        ),
        migrations.AddField(
            model_name='subject',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров (автоматически увеличивается)', verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS класс иконки', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active', 'is_popular'], name='teachers_su_is_acti_0214d9_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['-search_count'], name='teachers_su_search__4ee583_idx'),
        ),
        migrations.AddField(
            model_name='subjectsearchlog',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='teachers.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='subjectsearchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_searches', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='subjectcategory',
            index=models.Index(fields=['is_active', 'order'], name='teachers_su_is_acti_47f595_idx'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='teachers.subject', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='teachers.subjectcategory', verbose_name='Категория'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category', 'is_active'], name='teachers_su_categor_445435_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsearchlog',
            index=models.Index(fields=['subject', '-created_at'], name='teachers_su_subject_81f065_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsearchlog',
            index=models.Index(fields=['user', '-created_at'], name='teachers_su_user_id_4657a3_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsearchlog',
            index=models.Index(fields=['-created_at'], name='teachers_su_created_171a20_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsearchlog',
            index=models.Index(fields=['session_key', '-created_at'], name='teachers_su_session_07f18c_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', '-last_used'], name='teachers_sa_user_id_cebab8_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['is_active', '-last_used'], name='teachers_sa_is_acti_f79e3d_idx'),
        ),
    ]
