# Generated by Django 4.2 on 2025-11-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_add_subject_categories_fixed'),
        ('teachers', '0011_viewcounter'),
    ]

    operations = [
    ]
