# Generated by Django 4.2 on 2025-11-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_merge_20251114_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='savedsearch',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='subjectsearchlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог поиска предметов', 'verbose_name_plural': 'Логи поиска предметов'},
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='teachers_su_is_acti_0214d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='teachers_su_search__4ee583_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectcategory',
            name='teachers_su_is_acti_47f595_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectsearchlog',
            name='teachers_su_subject_81f065_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectsearchlog',
            name='teachers_su_user_id_4657a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectsearchlog',
            name='teachers_su_session_07f18c_idx',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='search_count',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='subjectsearchlog',
            name='filters_used',
        ),
        migrations.RemoveField(
            model_name='subjectsearchlog',
            name='result_count',
        ),
        migrations.RemoveField(
            model_name='subjectsearchlog',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='subjectsearchlog',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='subjectsearchlog',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectsearchlog',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='subjectsearchlog',
            name='found_results_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Найдено результатов'),
        ),
        migrations.AddField(
            model_name='subjectsearchlog',
            name='query',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Поисковый запрос'),
        ),
        migrations.AddField(
            model_name='subjectsearchlog',
            name='selected_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.subject', verbose_name='Выбранный предмет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS класс иконки', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Популярный предмет (показывать в топе)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Цвет в формате HEX (#3B82F6)', max_length=7),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS класс иконки (например, fas fa-calculator)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='subjectsearchlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата поиска'),
        ),
        migrations.AlterField(
            model_name='viewcounter',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_popular', 'is_active'], name='teachers_su_is_popu_f55229_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsearchlog',
            index=models.Index(fields=['query', '-created_at'], name='teachers_su_query_94f0a0_idx'),
        ),
        migrations.DeleteModel(
            name='SavedSearch',
        ),
    ]
