# Generated by Django 4.2 on 2025-11-19 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_remove_savedsearch_city_remove_savedsearch_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок сообщения')),
                ('content', models.TextField(verbose_name='Содержание сообщения')),
                ('message_type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('success', 'Успех'), ('danger', 'Важно'), ('announcement', 'Объявление')], default='info', max_length=20, verbose_name='Тип сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('show_to_all', models.BooleanField(default=True, verbose_name='Показывать всем пользователям')),
                ('show_to_teachers', models.BooleanField(default=True, verbose_name='Показывать учителям')),
                ('show_to_students', models.BooleanField(default=True, verbose_name='Показывать ученикам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем выше в списке', verbose_name='Приоритет')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
            options={
                'verbose_name': 'Сообщение платформы',
                'verbose_name_plural': 'Сообщения платформы',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.platformmessage', verbose_name='Сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочитанное сообщение',
                'verbose_name_plural': 'Прочитанные сообщения',
                'unique_together': {('user', 'message')},
            },
        ),
    ]
