# Generated by Django 5.2.9 on 2026-01-07 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_chatroom_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткий заголовок уведомления', max_length=200, verbose_name='Заголовок')),
                ('short_text', models.CharField(help_text='Текст для отображения в списке уведомлений', max_length=300, verbose_name='Краткий текст')),
                ('full_text', models.TextField(help_text='Подробное описание уведомления', verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, help_text='Опциональное изображение к уведомлению', null=True, upload_to='notifications/', verbose_name='Изображение')),
                ('action_url', models.URLField(blank=True, help_text='URL для перехода при клике (опционально)', null=True, verbose_name='Ссылка действия')),
                ('target', models.CharField(choices=[('all', 'Все пользователи'), ('students', 'Только ученики'), ('teachers', 'Только учителя'), ('admins', 'Только администраторы')], default='all', max_length=20, verbose_name='Целевая аудитория')),
                ('is_active', models.BooleanField(default=True, help_text='Только активные уведомления видны пользователям', verbose_name='Активно')),
                ('priority', models.IntegerField(default=0, help_text='Чем выше число, тем выше в списке. 0 = обычный приоритет', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_users', to='teachers.notification', verbose_name='Уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочитанное уведомление',
                'verbose_name_plural': 'Прочитанные уведомления',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_active', 'target'], name='teachers_no_is_acti_9ae983_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-priority', '-created_at'], name='teachers_no_priorit_be51aa_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationread',
            index=models.Index(fields=['user', 'notification'], name='teachers_no_user_id_d7fe60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together={('user', 'notification')},
        ),
    ]
