# Generated by Django 4.2 on 2025-11-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_platformmessage_usermessageread'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformmessage',
            name='show_to_guests',
            field=models.BooleanField(default=True, help_text='Если включено, сообщение будет видно неавторизованным пользователям', verbose_name='Показывать гостям (незарегистрированным)'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['-priority', '-created_at'], name='teachers_pl_priorit_f531fc_idx'),
        ),
        migrations.AddIndex(
            model_name='platformmessage',
            index=models.Index(fields=['is_active', 'expires_at'], name='teachers_pl_is_acti_65b1d9_idx'),
        ),
    ]
