# Generated by Django 5.2.9 on 2026-01-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_notification_notificationread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Если указан, уведомление будет видно только этому пользователю', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Конкретный пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target',
            field=models.CharField(choices=[('all', 'Все пользователи'), ('students', 'Только ученики'), ('teachers', 'Только учителя'), ('admins', 'Только администраторы'), ('specific_user', 'Конкретный пользователь')], default='all', max_length=20, verbose_name='Целевая аудитория'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_user', 'is_active'], name='teachers_no_target__525fe5_idx'),
        ),
    ]
