# Generated by Django 5.2.9 on 2026-01-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0017_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='weekly_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Индивидуальное расписание для каждого дня недели', null=True),
        ),
    ]
