# Generated by Django 5.2.9 on 2026-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_teacherprofile_weekly_schedule'),
    ]

    operations = [
        # Delete ChatMessage first (has FK to ChatRoom), then ChatRoom
        # This avoids SQLite's _remake_table issue with index/field removal order
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        # TeacherProfile changes
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['-ranking_score', '-rating', '-created_at'], 'verbose_name': 'Профиль учителя', 'verbose_name_plural': 'Профили учителей'},
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ranking_score',
            field=models.PositiveIntegerField(default=0, help_text='Приоритет в выдаче (0-100). Рассчитывается автоматически.'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['-ranking_score', '-rating', '-created_at'], name='teachers_te_ranking_9d8170_idx'),
        ),
        # Message enhancements
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-created_at'], name='teachers_me_convers_31e670_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='teachers_me_sender__ad309c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='teachers_me_is_read_51d587_idx'),
        ),
    ]
