# Generated by Django 5.2.12 on 2026-03-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_remove_chatmessage_room_remove_chatmessage_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['-is_featured', '-ranking_score', '-rating', '-created_at'], 'verbose_name': 'Профиль учителя', 'verbose_name_plural': 'Профили учителей'},
        ),
        migrations.RemoveIndex(
            model_name='teacherprofile',
            name='teachers_te_ranking_9d8170_idx',
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['-is_featured', '-ranking_score', '-rating'], name='teachers_te_is_feat_305718_idx'),
        ),
    ]
