# Generated by Django 5.2.12 on 2026-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_alter_teacherprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL видео-визитки в облачном хранилище', max_length=500, null=True),
        ),
    ]
