# Generated by Django 5.2.12 on 2026-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_add_video_url_to_teacherprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('morning', 'Утро'), ('evening', 'Вечер')], max_length=10, verbose_name='Период')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbek'), ('en', 'English')], max_length=2, verbose_name='Язык')),
                ('text', models.TextField(help_text='Поддерживается Markdown: *жирный*, _курсив_. Можно использовать эмодзи и переводы строк.', verbose_name='Текст сообщения')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено — шаблон не попадает в рассылку.', verbose_name='Активен')),
                ('note', models.CharField(blank=True, default='', help_text='Необязательное описание — только для вас.', max_length=200, verbose_name='Заметка для админа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Шаблон ежедневного напоминания',
                'verbose_name_plural': 'Шаблоны ежедневных напоминаний',
                'ordering': ['period', 'language', '-is_active', '-updated_at'],
                'indexes': [models.Index(fields=['period', 'language', 'is_active'], name='teachers_da_period_9d9512_idx')],
            },
        ),
    ]
