# Generated by Django 5.2.12 on 2026-05-19 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_search_text_profileview_dedup_wizard_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('held', 'Зарезервирован (ожидает подтверждения)'), ('booked', 'Забронирован'), ('blocked', 'Заблокирован учителем')], db_index=True, default='free', max_length=10, verbose_name='Статус')),
                ('hold_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='teachers.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения учителя'), ('confirmed', 'Подтверждено'), ('completed', 'Завершён'), ('cancelled_by_student', 'Отменено учеником'), ('cancelled_by_teacher', 'Отменено учителем'), ('rescheduled', 'Перенесено'), ('expired', 'Hold истёк (не подтверждено в 15 мин)'), ('no_show_student', 'Ученик не пришёл'), ('no_show_teacher', 'Учитель не пришёл')], db_index=True, default='pending', max_length=25)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('student_message', models.TextField(blank=True, help_text='Сообщение от ученика при бронировании', max_length=1000)),
                ('teacher_reply', models.TextField(blank=True, help_text='Комментарий учителя при подтверждении/отказе', max_length=1000)),
                ('is_trial', models.BooleanField(default=False, verbose_name='Пробный урок')),
                ('meeting_url', models.URLField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='teachers.subject', verbose_name='Предмет')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='teachers.timeslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Бронирование / Урок',
                'verbose_name_plural': 'Бронирования / Уроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['teacher', 'start_at'], name='teachers_ti_teacher_21a3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['status', 'hold_expires_at'], name='teachers_ti_status_c482bc_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['teacher', 'status', 'start_at'], name='teachers_ti_teacher_74c49d_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='timeslot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hold_expires_at__isnull', False), ('status', 'held')), models.Q(('status', 'held'), _negated=True), _connector='OR'), name='timeslot_hold_consistency'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', '-created_at'], name='teachers_bo_student_257cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='teachers_bo_status_a6f1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='teachers_bo_status_f8e917_idx'),
        ),
    ]
