# Generated by Django 5.2.12 on 2026-05-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_booking_fk_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonReminderSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('24h', 'За 24 часа'), ('3h', 'За 3 часа'), ('10min', 'За 10 минут')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channels', models.CharField(blank=True, default='', help_text='Каналы через запятую: email,in_app,telegram', max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_sent', to='teachers.booking')),
            ],
            options={
                'verbose_name': 'Отправленное напоминание',
                'verbose_name_plural': 'Отправленные напоминания',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['booking', 'kind'], name='teachers_le_booking_dc2597_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking', 'kind'), name='unique_reminder_per_booking_kind')],
            },
        ),
    ]
