# Generated by Django 5.2.13 on 2026-05-20 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_user_uniq_user_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Если уведомление о брони — позволяет подтвердить/отклонить прямо из уведомления', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='teachers.booking', verbose_name='Связанное бронирование'),
        ),
    ]
