# Generated by Django 5.2.13 on 2026-05-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_notification_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения учителя'), ('confirmed', 'Подтверждено'), ('completed', 'Завершён'), ('cancelled_by_student', 'Отменено учеником'), ('cancelled_by_teacher', 'Отменено учителем'), ('rescheduled', 'Перенесено'), ('expired', 'Заявка истекла (не подтверждена до начала урока)'), ('no_show_student', 'Ученик не пришёл'), ('no_show_teacher', 'Учитель не пришёл')], db_index=True, default='pending', max_length=25),
        ),
    ]
