# Generated by Django 5.2.13 on 2026-05-21 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='Урок, после которого оставлен отзыв', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='teachers.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Проверенный отзыв (был реальный урок)'),
        ),
    ]
