# Generated by Django 5.2.12 on 2026-05-24 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0031_review_booking_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubject',
            name='trial_duration_minutes',
            field=models.PositiveSmallIntegerField(choices=[(30, '30 минут'), (60, '60 минут')], default=60, help_text='Длительность пробного урока (30 или 60 минут)'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='trial_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена платного пробного урока в сумах (не указывается, если пробный бесплатный)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='is_free_trial',
            field=models.BooleanField(default=True, help_text='Бесплатное пробное занятие'),
        ),
    ]
