# Generated by Django 5.2.12 on 2026-05-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_transaction_related_subscription_and_more'),
        ('teachers', '0032_add_trial_lesson_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='billing.subscription', verbose_name='Подписка'),
        ),
    ]
