# Generated by Django 5.2.12 on 2026-05-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_booking_subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['teacher', '-created_at'], name='teachers_re_teacher_388f49_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['student', '-created_at'], name='teachers_re_student_630a71_idx'),
        ),
    ]
