# Generated by Django 5.2.12 on 2026-05-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='trial_price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Снэпшот цены платного пробного на момент бронирования. NULL = бесплатный или не пробный.', max_digits=12, null=True, verbose_name='Оплачено за пробный'),
        ),
    ]
