# Generated by Django 5.2.12 on 2026-06-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_booking_trial_price_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
