# Generated by Django 5.2.12 on 2026-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0036_booking_student_joined_at_booking_teacher_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_present_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='teacher_present_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
