# Generated by Django 5.2.12 on 2026-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_remove_transaction_billing_tra_type_69ac37_idx_and_more'),
        ('teachers', '0037_booking_student_present_seconds_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['subscription', 'status'], name='teachers_bo_subscri_f6b031_idx'),
        ),
    ]
