# Generated by Django 5.2.12 on 2026-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0038_booking_teachers_bo_subscri_f6b031_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teachersubject',
            index=models.Index(fields=['hourly_rate'], name='teachers_te_hourly__1e51c0_idx'),
        ),
    ]
