# Generated by Django 5.2.12 on 2026-06-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0039_teachersubject_teachers_te_hourly__1e51c0_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='rescheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
