# Generated by Django 5.2.12 on 2026-06-03 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0040_booking_reschedule_count_booking_rescheduled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_opt_outs', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_opt_outs', to='teachers.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Отказ ученика от лида',
                'verbose_name_plural': 'Отказы учеников от лидов',
                'indexes': [models.Index(fields=['teacher', 'student'], name='teachers_le_teacher_4389a8_idx')],
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
