# Generated by Django 5.2.12 on 2026-06-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0041_leadoptout'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'Общее'), ('booking', 'Бронирование'), ('lesson', 'Урок'), ('payment_in', 'Пополнение'), ('payment_out', 'Списание'), ('review', 'Отзыв'), ('moderation', 'Модерация'), ('reminder', 'Напоминание'), ('subscription', 'Подписка'), ('success', 'Успех'), ('warning', 'Предупреждение')], default='general', help_text='Определяет иконку уведомления в интерфейсе', max_length=20, verbose_name='Категория'),
        ),
    ]
