# Generated by Django 5.2.12 on 2026-06-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0042_notification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_show_forgiven',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения учителя'), ('confirmed', 'Подтверждено'), ('completed', 'Завершён'), ('cancelled_by_student', 'Отменено учеником'), ('cancelled_by_teacher', 'Отменено учителем'), ('rescheduled', 'Перенесено'), ('expired', 'Заявка истекла (не подтверждена до начала урока)'), ('no_show_student', 'Ученик не пришёл'), ('no_show_teacher', 'Учитель не пришёл'), ('not_held', 'Не состоялся (никто не пришёл)')], db_index=True, default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('join_teacher', 'Учитель подключился'), ('join_student', 'Ученик подключился'), ('settle_completed', 'Урок проведён'), ('settle_no_show_teacher', 'Неявка учителя'), ('no_show_forgiven', 'Неявка ученика прощена'), ('no_show_consumed', 'Неявка ученика — урок списан'), ('settle_not_held', 'Урок не состоялся'), ('warning_sent', 'Отправлено предупреждение'), ('payout', 'Выплата учителю'), ('refund', 'Возврат ученику')], db_index=True, max_length=32)),
                ('actor', models.CharField(blank=True, default='system', max_length=16)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='teachers.booking')),
            ],
            options={
                'verbose_name': 'Событие урока',
                'verbose_name_plural': 'События уроков',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='teachers_le_booking_4b8875_idx')],
            },
        ),
    ]
