# Generated by Django 5.2.12 on 2026-06-10 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0045_alter_booking_student_alter_timeslot_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='teachers.timeslot', verbose_name='Слот'),
        ),
    ]
