# Generated by Django 5.2.12 on 2026-06-10 08:17
#
# Аудит 2026-06-10 CRIT-4: b-tree индекс на search_text (TextField).
#
# Поиск идёт через LIKE '%…%' (search_text__contains) — b-tree такой предикат
# не использует вовсе. Хуже: search_text у TeacherProfile (имя + bio до 1000
# символов, кириллица в UTF-8 = 2 байта/символ) реально превышает лимит
# индексной строки b-tree PostgreSQL (~2704 байта) → save() профиля падал бы
# с «index row size exceeds maximum». Убираем b-tree; на PostgreSQL вместо
# него создаём GIN(gin_trgm_ops) — он ускоряет LIKE '%…%' и не имеет лимита
# на длину строки. На SQLite (dev) GIN-часть — no-op.
#
# DROP делаем через IF EXISTS по всем историческим именам: в старых базах
# индексы из 0024 существуют под legacy-именами (teachers_tp_search_idx /
# teachers_su_search__sbj_idx), потому что файл 0024 правился после применения.

from django.db import migrations, models

BTREE_INDEX_NAMES = [
    # имена из текущего файла 0024
    'teachers_su_search__7b9542_idx',
    'teachers_te_search__6fc140_idx',
    # legacy-имена в базах, мигрированных ранней версией 0024
    'teachers_su_search__sbj_idx',
    'teachers_tp_search_idx',
]

GIN_INDEXES = [
    # (имя индекса, таблица)
    ('teachers_teacherprofile_search_text_trgm', 'teachers_teacherprofile'),
    ('teachers_subject_search_text_trgm', 'teachers_subject'),
]


def drop_btree_indexes(apps, schema_editor):
    for name in BTREE_INDEX_NAMES:
        schema_editor.execute(f'DROP INDEX IF EXISTS {name}')


def recreate_btree_indexes(apps, schema_editor):
    # Обратная миграция: восстанавливаем b-tree под каноническими именами.
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS teachers_su_search__7b9542_idx '
        'ON teachers_subject (search_text)'
    )
    schema_editor.execute(
        'CREATE INDEX IF NOT EXISTS teachers_te_search__6fc140_idx '
        'ON teachers_teacherprofile (search_text)'
    )


def create_trgm_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    # Требует права на CREATE EXTENSION (на managed-PG обычно есть).
    # Если прав нет — миграция упадёт громко: расширение ставит DBA вручную,
    # затем migrate повторяется. Тихо пропускать нельзя — останемся без индекса.
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    for name, table in GIN_INDEXES:
        schema_editor.execute(
            f'CREATE INDEX IF NOT EXISTS {name} '
            f'ON {table} USING gin (search_text gin_trgm_ops)'
        )


def drop_trgm_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    for name, _table in GIN_INDEXES:
        schema_editor.execute(f'DROP INDEX IF EXISTS {name}')


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0046_alter_booking_slot'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='subject',
                    name='teachers_su_search__7b9542_idx',
                ),
                migrations.RemoveIndex(
                    model_name='teacherprofile',
                    name='teachers_te_search__6fc140_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(drop_btree_indexes, recreate_btree_indexes),
            ],
        ),
        migrations.RunPython(create_trgm_indexes, drop_trgm_indexes),
    ]
