# Generated by Django 5.2.12 on 2026-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_multicardinvoice_user'),
        ('teachers', '0048_timeslot_overlap_exclusion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='teachers_me_is_read_51d587_idx',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['student', 'status'], name='teachers_bo_student_1debc3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['teacher', 'is_active', '-updated_at'], name='teachers_co_teacher_4aa968_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['student', 'is_active', '-updated_at'], name='teachers_co_student_54b7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['conversation'], name='message_unread_by_conv_idx'),
        ),
    ]
