# Generated by Django 5.2.12 on 2026-06-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0049_remove_message_teachers_me_is_read_51d587_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='leads_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
