# Generated by Django 5.2.12 on 2026-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0050_teacherprofile_leads_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (английский)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_uz',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название (узбекский)'),
        ),
    ]
