# Generated by Django 5.2.12 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0054_backfill_student_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Опубликовано'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=10)),
                ('message_id', models.BigIntegerField(blank=True, help_text='ID опубликованного поста в канале', null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_post', to='teachers.teacherprofile')),
            ],
            options={
                'verbose_name': 'Публикация в канале',
                'verbose_name_plural': 'Публикации в канале',
                'ordering': ['-created_at'],
            },
        ),
    ]
