# Generated by Django 5.2.12 on 2026-07-06 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0055_teacherchannelpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='teachers.lessonfile', verbose_name='Вложение')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='teachers.booking', verbose_name='Урок')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение чата урока',
                'verbose_name_plural': 'Сообщения чата урока',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='teachers_le_booking_a7d288_idx')],
            },
        ),
    ]
