# Generated by Django 5.2.12 on 2026-07-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0056_lessonchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin_message',
            field=models.BooleanField(default=False, verbose_name='Сообщение от поддержки'),
        ),
    ]
